'use client';
import {useEffect,useState} from 'react';
import {ArrowLeft,ExternalLink} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Skeleton} from '@/components/ui/skeleton';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Table,TableHeader,TableBody,TableHead,TableRow,TableCell} from '@/components/ui/table';
import {segments,epoch,type Observation} from '@/lib/history';
import {localUserHeaders} from '@/lib/local-user';

type Window={minutes:number;status:string;score_change:number|null;comment_change:number|null;max_gap_seconds?:number;elapsed_minutes?:number};
type History={title:string;status:string;as_of:string;latest:Observation;windows:Window[];evidence:Observation[]};
type Channel={qualifies:boolean;recent_change:number;baseline_change:number;rate_multiple:number;rate_floor_applied:boolean;reasons:string[];recent_rate_per_minute:number;baseline_rate_per_minute:number;excess_change:number};
type Explanation={story:{status:string;reason:string;channels:Record<string,Channel>;sampling?:{max_gap_seconds:number;recent_minutes:number;baseline_minutes:number}}};
type LockedPrediction={id:string;call:'yes'|'no';confidence:number;expires_at:string};
type Pageview={date:string;views:number};
type WikipediaContext={status:'found'|'not_found'|'unavailable';provider:string;checked_at:string;note:string;article?:{title:string;description:string|null;url:string};pageviews?:{status:'available'|'unavailable';daily:Pageview[];total_14_days?:number;recent_7_days?:number;prior_7_days?:number}};
const clock=(x:string|number)=>new Date(typeof x==='number'?x:epoch(x)).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'});
const sign=(x:number|null)=>x===null?'—':(x>0?'+':'')+x;
const quality:Record<string,string>={complete:'Sampling complete',insufficient_history:'Not enough history',sampling_gap:'Contains a sampling gap',stale:'Last observation is stale',missing_boundary:'Missing a comparison sample',sparse_samples:'Too few observations',counter_decreased:'Counter decreased',low_volume:'Too little recent growth',not_accelerating:'Below the acceleration threshold',low_excess:'Too little growth above baseline'};
async function request<T>(path:string):Promise<T>{const r=await fetch('/api/pulse/'+path);const data:unknown=await r.json();if(!r.ok)throw new Error((data as {detail?:string}).detail||'Could not load this story');return data as T}
function HistoryChart({rows,metric}:{rows:Observation[];metric:'score'|'comments'}){
 const {lines,gaps}=segments(rows,metric);const points=lines.flat();if(!points.length)return <p>No samples available for this chart.</p>;
 const first=points[0].x,last=points.at(-1)!.x;const vals=points.map(p=>p.y),lo=Math.min(...vals),hi=Math.max(...vals);const padding=Math.max(1,(hi-lo)*.15);const min=Math.max(0,lo-padding),max=hi+padding;const x=(v:number)=>60+(v-first)/Math.max(1,last-first)*830,y=(v:number)=>210-(v-min)/(max-min)*170;
 return <><div className="chart-scroll"><svg className="history-chart" viewBox="0 0 950 260" aria-label={`${metric} totals over time. ${points.length} observations and ${gaps.length} gaps longer than three minutes. Raw values appear in the evidence table.`}>
 {[0,.5,1].map(v=><g key={v}><line x1="60" x2="890" y1={40+v*170} y2={40+v*170} stroke="#354035" strokeDasharray="3 6"/><text x="46" y={45+v*170} textAnchor="end" fill="#96a28e" fontSize="13">{Math.round(max-v*(max-min))}</text></g>)}
 {gaps.map(g=><rect key={g.from} x={x(g.from)} y="30" width={x(g.to)-x(g.from)} height="180" fill="#d1a65e" opacity=".12"/>)}
 {lines.map((line,i)=><g key={i}><polyline points={line.map(p=>`${x(p.x)},${y(p.y)}`).join(' ')} fill="none" stroke="#c5f46e" strokeWidth="2.5"/>{line.map(p=><circle key={p.x} cx={x(p.x)} cy={y(p.y)} r="3" fill="#c5f46e"><title>{clock(p.x)} · {p.y} {metric}</title></circle>)}</g>)}
 {[0,.5,1].map(v=><text key={v} x={60+v*830} y="246" textAnchor={v===0?'start':v===1?'end':'middle'} fill="#a7b29e" fontSize="13">{clock(first+v*(last-first))}</text>)}
 </svg></div><p className="chart-caption">Cumulative {metric==='score'?'HN score':'comment'} totals · your local time. {gaps.length?`${gaps.length} gap${gaps.length===1?'':'s'} over 3 minutes shown in amber; lines stop where observations are missing.`:'No gaps over 3 minutes in these samples.'} Points are observations, not individual events.</p></>
}
function PredictionPanel({id}:{id:number}){
 const [choice,setChoice]=useState<'yes'|'no'|null>(null),[confidence,setConfidence]=useState(50),[saved,setSaved]=useState<LockedPrediction|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const lock=async()=>{if(!choice)return;setBusy(true);setError('');try{const response=await fetch(`/api/pulse/v1/stories/${id}/predictions`,{method:'POST',headers:{'Content-Type':'application/json',...localUserHeaders()},body:JSON.stringify({call:choice,confidence})});const data=await response.json() as {prediction?:LockedPrediction;detail?:string};if(!response.ok)throw new Error(data.detail||'Could not lock your call.');setSaved(data.prediction||null)}catch(reason){setError(reason instanceof Error?reason.message:'Could not lock your call.')}finally{setBusy(false)}};
 if(saved)return <section className="prediction-panel locked"><p className="eyebrow lime">CALL LOCKED</p><h3>You called {saved.call.toUpperCase()} at {saved.confidence}% confidence.</h3><p>Pulse will check whether this story enters the top 10 HN signals by {new Date(saved.expires_at).toLocaleString()}.</p></section>;
 return <section className="prediction-panel"><p className="eyebrow">MAKE A 24-HOUR CALL</p><h3>Will this story enter Pulse’s top 10 HN signals?</h3><p>Pulse checks every five minutes for the next 24 hours. Your choice cannot be changed on this browser.</p><div className="call-choices"><Button variant={choice==='yes'?'default':'outline'} onClick={()=>setChoice('yes')}>YES</Button><Button variant={choice==='no'?'default':'outline'} onClick={()=>setChoice('no')}>NO</Button><Button disabled={!choice||busy} onClick={lock}>{busy?'Locking…':'Lock in call'}</Button></div><label className="confidence-control" htmlFor={`confidence-${id}`}><span>Your confidence <strong>{confidence}%</strong></span><input id={`confidence-${id}`} type="range" min="50" max="100" step="5" value={confidence} onChange={event=>setConfidence(Number(event.target.value))}/><small>Choose how sure you are before you lock the call.</small></label>{error&&<p className="prediction-error">{error}</p>}</section>;
}
function WikipediaPanel({context,error}:{context:WikipediaContext|null;error:string}){
 if(error)return <section className="wiki-panel unavailable"><p className="eyebrow">WIKIPEDIA REFERENCE</p><h3>Reference context is unavailable.</h3><p>{error}</p></section>;
 if(!context||context.status==='unavailable')return context?<section className="wiki-panel unavailable"><p className="eyebrow">WIKIPEDIA REFERENCE</p><h3>Reference context is unavailable.</h3><p>Pulse will try again when you reopen this investigation.</p></section>:null;
 if(context.status==='not_found'||!context.article)return <section className="wiki-panel unavailable"><p className="eyebrow">WIKIPEDIA REFERENCE</p><h3>No direct article match.</h3><p>Pulse did not use a weak automated match for this HN title.</p></section>;
 const views=context.pageviews?.daily||[];const max=Math.max(1,...views.map(day=>day.views));const total=context.pageviews?.total_14_days;
 return <section className="wiki-panel"><div className="section-heading"><div><p className="eyebrow">WIKIPEDIA REFERENCE</p><h3><a href={context.article.url} target="_blank" rel="noreferrer">{context.article.title} <ExternalLink size={14}/></a></h3></div><span className="mono">ON DEMAND</span></div>{context.article.description&&<p className="wiki-description">{context.article.description}</p>}{context.pageviews?.status==='available'?<><div className="view-summary"><strong>{total?.toLocaleString()} views</strong><span>last {views.length} complete UTC days</span></div><div className="pageview-bars" aria-label={`${context.article.title} daily Wikipedia page views for ${views.length} completed days. Total ${total} views.`}>{views.map(day=><span key={day.date} title={`${day.date}: ${day.views.toLocaleString()} views`} style={{height:`${Math.max(5,day.views/max*100)}%`}}/> )}</div><div className="view-dates"><span>{views.at(0)?.date}</span><span>{views.at(-1)?.date}</span></div></>:<p className="wiki-description">Recent page-view history was unavailable for this article.</p>}<p className="footnote">{context.note}</p></section>;
}
export default function Investigate({id,asOf,onBack}:{id:number;asOf:string;onBack:()=>void}){
 const [history,setHistory]=useState<History|null>(null),[explanation,setExplanation]=useState<Explanation|null>(null),[wikipedia,setWikipedia]=useState<WikipediaContext|null>(null),[error,setError]=useState(''),[explanationError,setExplanationError]=useState(''),[wikipediaError,setWikipediaError]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{let cancelled=false;setHistory(null);setError('');setExplanation(null);setExplanationError('');setWikipedia(null);setWikipediaError('');const q='?as_of='+encodeURIComponent(asOf);void Promise.allSettled([request<History>(`v1/stories/${id}/history${q}`),request<Explanation>(`v1/stories/${id}/explanation${q}`),request<WikipediaContext>(`v1/stories/${id}/wikipedia${q}`)]).then(([h,e,w])=>{if(cancelled)return;if(h.status==='fulfilled')setHistory(h.value);else setError(h.reason.message);if(e.status==='fulfilled')setExplanation(e.value);else setExplanationError(e.reason.message);if(w.status==='fulfilled')setWikipedia(w.value);else setWikipediaError(w.reason.message)});return()=>{cancelled=true}},[id,asOf,retry]);
 const story=explanation?.story;
 return <section className="investigate"><Button variant="ghost" onClick={onBack} className="back"><ArrowLeft/> Back to radar</Button><div className="detail-heading"><p className="eyebrow">HACKER NEWS / STORY #{id}</p><h2>{history?.title||'Loading story evidence…'}</h2><div className="detail-meta"><span>Snapshot {new Date(asOf).toLocaleString()}</span><a href={`https://news.ycombinator.com/item?id=${id}`} target="_blank" rel="noreferrer">Open discussion <ExternalLink size={14}/></a></div></div><PredictionPanel id={id}/>
 {error?<div role="alert" className="notice error">{error}<Button variant="outline" onClick={()=>setRetry(x=>x+1)}>Try again</Button></div>:!history?<Skeleton className="h-64 w-full"/>:<><div className="detail-layout"><div><section className="chart-panel"><div className="section-heading"><h3>Attention history</h3><span className="mono">LAST 63 MINUTES</span></div><Tabs defaultValue="comments"><TabsList aria-label="Chart metric"><TabsTrigger value="comments">Comments</TabsTrigger><TabsTrigger value="score">HN score</TabsTrigger></TabsList><TabsContent value="comments"><HistoryChart rows={history.evidence} metric="comments"/></TabsContent><TabsContent value="score"><HistoryChart rows={history.evidence} metric="score"/></TabsContent></Tabs></section>
 <div className="change-grid">{history.windows.map(w=><section className="change-card" key={w.minutes}><p className="eyebrow">{w.minutes} MINUTE CHANGE</p><strong>{sign(w.comment_change)}<span> comments</span></strong><p>{sign(w.score_change)} score points</p><span className={w.status==='complete'?'fresh':'amber'}>{quality[w.status]||w.status}</span>{w.elapsed_minutes!==undefined&&<small>Across {w.elapsed_minutes.toFixed(1)} sampled minutes</small>}</section>)}</div><WikipediaPanel context={wikipedia} error={wikipediaError}/></div>
 <aside className="detail-aside"><section className="side-card"><p className="eyebrow">WHY THIS STORY</p><h3 className={story?.status==='candidate'?'lime':''}>{story?.status==='candidate'?'A change in pace.':story?.status==='quiet'?'Below the thresholds.':'Not enough reliable data.'}</h3>{explanationError?<p>{explanationError}</p>:story?.status==='excluded'?<p>{quality[story.reason]||story.reason.replaceAll('_',' ')}. We don’t infer acceleration from missing data.</p>:Object.entries(story?.channels||{}).map(([name,c])=><div className="channel" key={name}><h4>{name==='score'?'HN score':'Comments'} <span className={c.qualifies?'lime':'muted'}>{c.qualifies?'Qualifies':'Not qualifying'}</span></h4><strong>{c.rate_multiple.toFixed(2)}×</strong><p>{c.rate_floor_applied?'Compared with the minimum baseline rate':'Compared with the previous rate'}</p><dl><div><dt>Recent growth</dt><dd>{sign(c.recent_change)}</dd></div><div><dt>Earlier growth</dt><dd>{sign(c.baseline_change)}</dd></div><div><dt>Above expectation</dt><dd>{c.excess_change.toFixed(1)}</dd></div></dl>{c.reasons.map(r=><small key={r}>{quality[r]||r}</small>)}</div>)}<p className="footnote">A comparison of recent observations. Not a forecast or a Pulse Score.</p></section></aside></div>
 <section className="evidence"><div className="section-heading"><h3>The original observations</h3><span className="mono">{history.evidence.length} SAMPLES</span></div><p className="muted">Collection timestamps in your local time. Totals can decrease; gaps mean we did not observe what happened in between.</p><Table><TableHeader><TableRow><TableHead>COLLECTED</TableHead><TableHead>HN SCORE</TableHead><TableHead>COMMENTS</TableHead><TableHead>SINCE PREVIOUS</TableHead></TableRow></TableHeader><TableBody>{history.evidence.map((row,i)=>{const gap=i?(epoch(row.observed_at)-epoch(history.evidence[i-1].observed_at))/1000:null;return <TableRow key={row.event_id}><TableCell>{clock(row.observed_at)}</TableCell><TableCell>{row.score}</TableCell><TableCell>{row.comments}</TableCell><TableCell className={gap&&gap>180?'amber':''}>{gap===null?'First sample':`${(gap/60).toFixed(1)} min${gap>180?' · gap':''}`}</TableCell></TableRow>})}</TableBody></Table></section></>}
 </section>
}
