'use client';
import { useEffect, useState, useCallback, useRef } from 'react';
import { Activity, ArrowUpRight, RefreshCw, Radio, CircleHelp, Target } from 'lucide-react';
import { Button } from '@/components/ui/button';
import Investigate from './investigate';
import { Empty } from '@/components/ui/empty';
import { Skeleton } from '@/components/ui/skeleton';
import { Table, TableBody, TableRow, TableHead, TableHeader, TableCell } from '@/components/ui/table';
import Calls from './calls';

type Story = { story_id: number; title: string; observed_at: string; score: number; comments: number; fresh: boolean };
type Channel = { qualifies:boolean; recent_change:number; baseline_change:number; rate_multiple:number; rate_floor_applied:boolean; reasons:string[] };
type Candidate = { story_id:number; title:string; rank:number; channels:Record<string,Channel>; sampling:{ recent_minutes:number; baseline_minutes:number } };
type Radar = { as_of:string; summary:{ stories_evaluated:number; eligible:number; candidates:number; exclusions:Record<string,number> }; candidates:Candidate[] };
type Health = { status?:string; latest_observed_at?:string; detail?:string };
const utc = (s:string) => new Date(s.includes('T') ? s : s.replace(' ','T')+'Z');
const time = (s:string) => utc(s).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});
async function get<T>(path:string):Promise<T> { const r=await fetch('/api/pulse/'+path); const data: unknown=await r.json(); if(!r.ok) throw new Error((data as {detail?:string}).detail || 'Data is temporarily unavailable.'); return data as T; }
export default function Home(){
 const [radar,setRadar]=useState<Radar|null>(null),[stories,setStories]=useState<Story[]>([]),[health,setHealth]=useState<Health>({}),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [selected,setSelected]=useState<number|null>(null),[selectedAt,setSelectedAt]=useState(''),[view,setView]=useState<'radar'|'calls'>('radar');
 const inFlight=useRef(false);
 const openStory=(id:number)=>{const at=radar?.as_of||new Date().toISOString();setView('radar');setSelectedAt(at);setSelected(id);window.history.pushState({},'',`?story=${id}&as_of=${encodeURIComponent(at)}`);window.scrollTo(0,0)};
 const back=()=>{setSelected(null);setView('radar');window.history.pushState({},'','/');window.scrollTo(0,0)};
 useEffect(()=>{const readUrl=()=>{const q=new URLSearchParams(window.location.search);const id=Number(q.get('story'));const at=q.get('as_of');if(Number.isSafeInteger(id)&&id>0&&at&&Number.isFinite(Date.parse(at))){setSelected(id);setSelectedAt(at)}else{setSelected(null)}};readUrl();window.addEventListener('popstate',readUrl);return()=>window.removeEventListener('popstate',readUrl)},[]);
 const refresh=useCallback(async()=>{if(inFlight.current)return;inFlight.current=true;setBusy(true);try{const [r,h]=await Promise.all([get<Radar>('v1/radar?limit=100'),fetch('/api/pulse/health').then(r=>r.json() as Promise<Health>)]);const list=await get<{stories:Story[]}>('v1/stories?limit=100&as_of='+encodeURIComponent(r.as_of));setRadar(r);setStories(list.stories);setHealth(h);setError('');}catch(e){setError(e instanceof Error?e.message:'Could not load data');}finally{inFlight.current=false;setBusy(false);}},[]);
 useEffect(()=>{void refresh();const id=setInterval(()=>void refresh(),30000);return()=>clearInterval(id)},[refresh]);
 return <><header className="mast"><button onClick={back} className="brand" aria-label="Return to Pulse radar"><Activity size={25}/><span>PULSE<span className="brand-dot">.</span></span></button><button onClick={()=>{setSelected(null);setView('radar')}} className={view==='radar'?'nav-active':'nav-link'}><Radio size={16}/> Radar</button><button onClick={()=>{setSelected(null);setView('calls');window.history.pushState({},'','/')}} className={view==='calls'?'nav-active':'nav-link'}><Target size={16}/> My calls</button><div className="mast-right"><span className={'live-dot '+(health.status==='ok'&&!error?'':'off')}/>{health.status==='ok'&&!error?'Collecting now':'Collection unverified'}<span className="local-label">LOCAL</span></div></header>
 <main className="workspace">{view==='calls'&&!selected?<Calls onOpen={openStory}/>:<><div className="page-heading"><div><p className="eyebrow">INTERNET ATTENTION / HACKER NEWS</p><h1>{selected?'Investigate':'On the radar'}<span className="heading-dot">.</span></h1><p className="intro">{selected?'Trace the attention back to its evidence.':'Follow the first signs of accelerating attention.'}</p></div>{!selected&&<Button variant="outline" onClick={refresh} disabled={busy} className="refresh"><RefreshCw className={busy?'spin':''}/> {busy?'Updating':'Refresh'} </Button>}</div>
 {error&&<div role="alert" className="notice error">{error} {radar&&'Showing the last successful snapshot.'}</div>}
 {selected?<Investigate id={selected} asOf={selectedAt} onBack={back}/>:!radar&&!error?<div aria-label="Loading observations" className="loading"><Skeleton className="h-24 w-full"/><Skeleton className="h-64 w-full"/></div>:radar&&<><section className="metrics"><div><span>Stories observed</span><strong>{radar.summary.stories_evaluated}</strong></div><div><span>Usable baselines</span><strong>{radar.summary.eligible}</strong></div><div><span>Accelerating</span><strong className="lime">{radar.summary.candidates}<ArrowUpRight size={28}/></strong></div><div><span>Snapshot · your time</span><strong className="clock">{time(radar.as_of)}</strong></div></section>
 <div className="radar-layout"><section><div className="section-heading"><h2><span className="tiny-pulse"/> Accelerating stories</h2><span className="mono">{String(radar.summary.candidates).padStart(2,'0')} SIGNALS</span></div>
 {radar.candidates.length?radar.candidates.map(c=><button key={c.story_id} className="signal-card" onClick={()=>openStory(c.story_id)}><span className="signal-number">{String(c.rank).padStart(2,'0')}</span><div><p className="eyebrow lime">ACCELERATING</p><h3>{c.title}</h3><p>{Object.entries(c.channels).filter(([,v])=>v.qualifies).map(([k,v])=>`+${v.recent_change} ${k==='score'?'score points':'comments'} · ${v.rate_multiple.toFixed(1)}× ${v.rate_floor_applied?'minimum baseline':'previous rate'}`).join(' / ')}</p></div><ArrowUpRight/></button>):<Empty className="quiet"><Radio size={32}/><h3>{radar.summary.eligible?'A quiet moment. Keep watching.':'Waiting for a usable baseline.'}</h3><p>{radar.summary.eligible?'No sampled stories meet the acceleration rules right now. Explore recent observations below.':'Stories need about 20 minutes of sufficiently continuous history before they can qualify.'}</p><span className="quiet-tag">No forced signals. Just the evidence.</span></Empty>}
 <div className="section-heading recent-heading"><h2>Recently observed</h2><span className="muted">Cumulative totals</span></div><Table className="story-table"><TableHeader><TableRow><TableHead>STORY</TableHead><TableHead>SCORE</TableHead><TableHead>COMMENTS</TableHead><TableHead>OBSERVED</TableHead><TableHead><span className="sr-only">Investigate</span></TableHead></TableRow></TableHeader><TableBody>{stories.map(s=><TableRow key={s.story_id}><TableCell><button className="story-link" onClick={()=>openStory(s.story_id)}>{s.title}</button><span className="source-label">Hacker News · #{s.story_id}</span></TableCell><TableCell className="number">{s.score}</TableCell><TableCell className="number">{s.comments}</TableCell><TableCell><span className={s.fresh?'fresh':'amber'}>{s.fresh?'●':'○'} {time(s.observed_at)}</span></TableCell><TableCell><Button variant="ghost" size="icon" aria-label={'Investigate '+s.title} onClick={()=>openStory(s.story_id)}><ArrowUpRight/></Button></TableCell></TableRow>)}</TableBody></Table></section>
 <aside><section className="side-card"><p className="eyebrow">THE SIGNAL, EXPLAINED</p><h3>A change in pace.</h3><p>We compare the last five minutes of score and comment growth with the preceding fifteen.</p><div className="baseline-visual"><span>PREVIOUS 15 MIN</span><span>LAST 5 MIN</span><div/><div/></div><p>Stories need meaningful growth and at least twice their baseline rate to qualify.</p><span className="footnote">Heuristic detection · not a virality prediction</span></section><section className="side-card coverage"><div className="section-heading"><h3>Collection quality</h3><CircleHelp size={17}/></div><p>Missing observations are not zero activity.</p>{Object.entries(radar.summary.exclusions).map(([reason,n])=><div className="quality-row" key={reason}><span>{reason.replaceAll('_',' ')}</span><strong>{n}</strong></div>)}{!Object.keys(radar.summary.exclusions).length&&<p className="lime">All observed stories have usable history.</p>}<div className="side-footer">Refreshes every 30 seconds.<br/>A bounded HN sample, not the whole internet.</div></section></aside></div></>}
 </>}</main><footer className="footer"><span>PULSE / EARLY SIGNALS, OPEN EVIDENCE</span><span>Hacker News · local prototype</span></footer></>;
}
